#!/usr/bin/env sh

source "$(dirname "$0")/pre-script"

mkdir "$1"
(
cd "$1"
curl -s "https://api.github.com/orgs/$1/repos?per_page=200" | \
    jq .[].clone_url | \
    xargs -n 1 git clone --mirror
)

