#!/usr/bin/env sh

if [[ -z "$1" ]]; then
	echo "Please enter a source repository name"
	exit 1
fi

if [[ -z "$2" ]]; then
	echo "Please enter a destination repository name"
	exit 1
fi

if [[ -d "$2" ]]; then
	echo "Repo $2 already exists"
	exit 1
fi

mv "$1" "$2"
echo "Successfully renamed repository $1 to $2"

